from .auth import router as auth_router
from .users import router as users_router
from .devices import router as devices_router
from .categories import router as categories_router
from .contracts import router as contracts_router
from .contract_reminders import router as contract_reminders_router
from .disinfection import router as disinfection_router
from .maintenance import router as maintenance_router
from .repairs import router as repairs_router
from .deposits import router as deposits_router
from .locking import router as locking_router
from .audit import router as audit_router
from .reservations import router as reservations_router
from .quotations import router as quotations_router
from .device_transfers import router as device_transfers_router
from .customer_credit_notes import router as customer_credit_notes_router
from .device_imports import router as device_imports_router
from .device_swaps import router as device_swaps_router
from .handovers import router as handovers_router
from .pricing_rules import router as pricing_rules_router
from .tasks import router as tasks_router
