"""initial_schema

Revision ID: 2aee1c0e7491
Revises: 
Create Date: 2026-06-09 00:34:07.570293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aee1c0e7491'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('daily_rental_rate', sa.Float(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('maintenance_cycle_days', sa.Integer(), nullable=False),
    sa.Column('disinfection_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('device_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_categories_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id_card', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id_card'), ['id_card'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('overdue_fee', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('deposit_refunded', sa.Boolean(), nullable=True),
    sa.Column('deposit_refund_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'ACTIVE', 'RENEWED', 'RETURNED', 'EXPIRED', 'OVERDUE', 'CANCELLED', name='contractstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commitment_batch_token', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_commitment_batch_token'), ['commitment_batch_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_contract_number'), ['contract_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_id'), ['id'], unique=False)

    op.create_table('device_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PREVIEWED', 'CONFIRMED', 'CANCELLED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_imports_batch_number'), ['batch_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_imports_id'), ['id'], unique=False)

    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='pricingrulestatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_rental_days', sa.Integer(), nullable=False),
    sa.Column('deposit_adjustment_factor', sa.Float(), nullable=False),
    sa.Column('overdue_daily_rate_multiplier', sa.Float(), nullable=False),
    sa.Column('allowed_customer_roles', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['device_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_rules_id'), ['id'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('rental_days', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('total_rental_fee', sa.Float(), nullable=False),
    sa.Column('total_deposit', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('estimated_total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'VOIDED', name='quotationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_quotation_number'), ['quotation_number'], unique=True)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_occupancy', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_warehouses_id'), ['id'], unique=False)

    op.create_table('contract_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'NO_ACTION_NEEDED', 'FOLLOW_UP_LATER', name='reminderstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_reminders_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_reminders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_reminders_status'), ['status'], unique=False)

    op.create_table('customer_credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('risk_tag', sa.Enum('DEPOSIT_DISPUTE', 'OVERDUE_RETURN', 'DEVICE_DAMAGE', 'PAYMENT_ISSUE', 'OTHER', name='risktag'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('related_contract_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_credit_notes_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_credit_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_credit_notes_risk_tag'), ['risk_tag'], unique=False)

    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('refund_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_method', sa.String(length=50), nullable=True),
    sa.Column('refund_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deductions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deposits_id'), ['id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('current_owner', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'REPAIR', 'DISINFECTION', 'LOCKED', 'RETIRED', name='devicestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('last_disinfection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['device_categories.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_serial_number'), ['serial_number'], unique=True)

    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal_rental', sa.Float(), nullable=True),
    sa.Column('subtotal_deposit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['device_categories.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotation_items_id'), ['id'], unique=False)

    op.create_table('tiered_discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pricing_rule_id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pricing_rule_id'], ['pricing_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiered_discounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiered_discounts_id'), ['id'], unique=False)

    op.create_table('contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_items_id'), ['id'], unique=False)

    op.create_table('device_import_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('purchase_date_str', sa.String(length=50), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('current_owner', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_code', sa.String(length=50), nullable=True),
    sa.Column('warehouse_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VALID', 'INVALID', 'IMPORTED', 'FAILED', 'SKIPPED', name='importitemstatus'), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['device_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_import_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_import_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_import_items_import_id'), ['import_id'], unique=False)

    op.create_table('device_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('lock_token', sa.String(length=100), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_locks_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_locks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_locks_lock_token'), ['lock_token'], unique=True)

    op.create_table('device_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('from_location_type', sa.Enum('WAREHOUSE', 'STORE', 'CUSTOMER', 'REPAIR', name='transferlocationtype'), nullable=False),
    sa.Column('from_location', sa.String(length=255), nullable=False),
    sa.Column('to_location_type', sa.Enum('WAREHOUSE', 'STORE', 'CUSTOMER', 'REPAIR', name='transferlocationtype'), nullable=False),
    sa.Column('to_location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', name='transferstatus'), nullable=False),
    sa.Column('transfer_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_transfers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_transfers_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_transfers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_transfers_status'), ['status'], unique=False)

    op.create_table('disinfection_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('disinfection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disinfectant_type', sa.String(length=100), nullable=False),
    sa.Column('disinfection_method', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('concentration', sa.String(length=50), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('is_qualified', sa.Boolean(), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disinfection_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disinfection_records_id'), ['id'], unique=False)

    op.create_table('handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handover_number', sa.String(length=50), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('handover_type', sa.Enum('OUTBOUND', 'RETURN', name='handovertype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'CONFIRMED', 'CANCELLED', name='handoverstatus'), nullable=False),
    sa.Column('appearance_description', sa.Text(), nullable=True),
    sa.Column('accessories', sa.JSON(), nullable=True),
    sa.Column('abnormal_remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_customer_id', sa.Integer(), nullable=True),
    sa.Column('staff_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_staff_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handovers_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_handover_number'), ['handover_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_handovers_handover_type'), ['handover_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handovers_status'), ['status'], unique=False)

    op.create_table('inventory_commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commitment_token', sa.String(length=100), nullable=False),
    sa.Column('batch_token', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('commitment_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['device_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_commitments', schema=None) as batch_op:
        batch_op.create_index('idx_commitment_batch_token', ['batch_token'], unique=False)
        batch_op.create_index('idx_commitment_device_dates', ['device_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('idx_commitment_device_reference_unique', ['device_id', 'reference_type', 'reference_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'confirmed')"), sqlite_where=sa.text("status IN ('pending', 'confirmed')"))
        batch_op.create_index('idx_commitment_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index('idx_commitment_warehouse_category', ['warehouse_id', 'category_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_batch_token'), ['batch_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_commitment_token'), ['commitment_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_commitment_type'), ['commitment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_reference_type'), ['reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_commitments_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('technician_name', sa.String(length=100), nullable=True),
    sa.Column('service_provider', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('work_performed', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_id'), ['id'], unique=False)

    op.create_table('repair_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fault_description', sa.Text(), nullable=False),
    sa.Column('fault_category', sa.String(length=100), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('diagnosis_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repair_plan', sa.Text(), nullable=True),
    sa.Column('repair_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repair_complete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('parts_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('handled_by_id', sa.Integer(), nullable=True),
    sa.Column('technician_notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('is_warranty', sa.Boolean(), nullable=True),
    sa.Column('warranty_expired', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['handled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_records_id'), ['id'], unique=False)

    op.create_table('device_swaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swap_number', sa.String(length=50), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('old_device_id', sa.Integer(), nullable=False),
    sa.Column('new_device_id', sa.Integer(), nullable=False),
    sa.Column('contract_item_id', sa.Integer(), nullable=False),
    sa.Column('fault_description', sa.Text(), nullable=False),
    sa.Column('fault_category', sa.String(length=100), nullable=True),
    sa.Column('old_daily_rate', sa.Float(), nullable=False),
    sa.Column('new_daily_rate', sa.Float(), nullable=False),
    sa.Column('keep_original_rate', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='deviceswapstatus'), nullable=False),
    sa.Column('repair_record_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['new_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['old_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['repair_record_id'], ['repair_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_swaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_swaps_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_swaps_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_swaps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_swaps_new_device_id'), ['new_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_swaps_old_device_id'), ['old_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_swaps_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_swaps_swap_number'), ['swap_number'], unique=True)

    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('MAINTENANCE', 'DISINFECTION', 'REPAIR', name='tasktype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLAIMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_record_id', sa.Integer(), nullable=True),
    sa.Column('disinfection_record_id', sa.Integer(), nullable=True),
    sa.Column('repair_record_id', sa.Integer(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_overdue', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['disinfection_record_id'], ['disinfection_records.id'], ),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], ),
    sa.ForeignKeyConstraint(['repair_record_id'], ['repair_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_tasks_id'), ['id'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='reservationstatus'), nullable=False),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('lock_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['lock_id'], ['device_locks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_reservation_number'), ['reservation_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_reservation_number'))
        batch_op.drop_index(batch_op.f('ix_reservations_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_device_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_customer_id'))

    op.drop_table('reservations')
    with op.batch_alter_table('maintenance_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_tasks_id'))

    op.drop_table('maintenance_tasks')
    with op.batch_alter_table('device_swaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_swaps_swap_number'))
        batch_op.drop_index(batch_op.f('ix_device_swaps_status'))
        batch_op.drop_index(batch_op.f('ix_device_swaps_old_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_swaps_new_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_swaps_id'))
        batch_op.drop_index(batch_op.f('ix_device_swaps_created_at'))
        batch_op.drop_index(batch_op.f('ix_device_swaps_contract_id'))

    op.drop_table('device_swaps')
    with op.batch_alter_table('repair_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_records_id'))

    op.drop_table('repair_records')
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_records_id'))

    op.drop_table('maintenance_records')
    with op.batch_alter_table('inventory_commitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_status'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_start_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_reference_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_reference_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_end_date'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_device_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_created_at'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_commitment_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_commitment_token'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_category_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_commitments_batch_token'))
        batch_op.drop_index('idx_commitment_warehouse_category')
        batch_op.drop_index('idx_commitment_reference')
        batch_op.drop_index('idx_commitment_device_reference_unique', postgresql_where=sa.text("status IN ('pending', 'confirmed')"), sqlite_where=sa.text("status IN ('pending', 'confirmed')"))
        batch_op.drop_index('idx_commitment_device_dates')
        batch_op.drop_index('idx_commitment_batch_token')

    op.drop_table('inventory_commitments')
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handovers_status'))
        batch_op.drop_index(batch_op.f('ix_handovers_id'))
        batch_op.drop_index(batch_op.f('ix_handovers_handover_type'))
        batch_op.drop_index(batch_op.f('ix_handovers_handover_number'))
        batch_op.drop_index(batch_op.f('ix_handovers_device_id'))
        batch_op.drop_index(batch_op.f('ix_handovers_created_at'))
        batch_op.drop_index(batch_op.f('ix_handovers_contract_id'))

    op.drop_table('handovers')
    with op.batch_alter_table('disinfection_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disinfection_records_id'))

    op.drop_table('disinfection_records')
    with op.batch_alter_table('device_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_transfers_status'))
        batch_op.drop_index(batch_op.f('ix_device_transfers_id'))
        batch_op.drop_index(batch_op.f('ix_device_transfers_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_transfers_created_at'))

    op.drop_table('device_transfers')
    with op.batch_alter_table('device_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_locks_lock_token'))
        batch_op.drop_index(batch_op.f('ix_device_locks_id'))
        batch_op.drop_index(batch_op.f('ix_device_locks_device_id'))

    op.drop_table('device_locks')
    with op.batch_alter_table('device_import_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_import_items_import_id'))
        batch_op.drop_index(batch_op.f('ix_device_import_items_id'))

    op.drop_table('device_import_items')
    with op.batch_alter_table('contract_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_items_id'))

    op.drop_table('contract_items')
    with op.batch_alter_table('tiered_discounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiered_discounts_id'))

    op.drop_table('tiered_discounts')
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotation_items_id'))

    op.drop_table('quotation_items')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_devices_id'))

    op.drop_table('devices')
    with op.batch_alter_table('deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposits_id'))

    op.drop_table('deposits')
    with op.batch_alter_table('customer_credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_credit_notes_risk_tag'))
        batch_op.drop_index(batch_op.f('ix_customer_credit_notes_id'))
        batch_op.drop_index(batch_op.f('ix_customer_credit_notes_customer_id'))

    op.drop_table('customer_credit_notes')
    with op.batch_alter_table('contract_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_contract_reminders_id'))
        batch_op.drop_index(batch_op.f('ix_contract_reminders_contract_id'))

    op.drop_table('contract_reminders')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_id'))
        batch_op.drop_index(batch_op.f('ix_warehouses_code'))

    op.drop_table('warehouses')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_quotation_number'))
        batch_op.drop_index(batch_op.f('ix_quotations_id'))

    op.drop_table('quotations')
    with op.batch_alter_table('pricing_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_rules_id'))

    op.drop_table('pricing_rules')
    with op.batch_alter_table('device_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_imports_id'))
        batch_op.drop_index(batch_op.f('ix_device_imports_batch_number'))

    op.drop_table('device_imports')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_contract_number'))
        batch_op.drop_index(batch_op.f('ix_contracts_commitment_batch_token'))

    op.drop_table('contracts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id_card'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('device_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_categories_id'))

    op.drop_table('device_categories')
    # ### end Alembic commands ###
